# ----------------------------------------------------------------------------------------
#
# Copyright (c) 2023, WSO2 LLC. (https://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 LLC. and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained
# herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
# You may not alter or remove any copyright or other notice from copies of this content.
#
# ----------------------------------------------------------------------------------------

wso2:
  subscription:
    username: ""
    password: ""
  
  deployment:
    ob:
      iam:
        # Container image configurations
        # If a custom image must be used, uncomment 'dockerRegistry' and provide its value
        # dockerRegistry: ""
        imageName: "wso2-obiam-toolkit-uk"
        imageTag: "1.0.0.21-acc3.0.0.95-is6.1.0.80-alpine"
        # Refer to the Kubernetes documentation on updating images (https://kubernetes.io/docs/concepts/containers/images/#updating-images)
        imagePullPolicy: Always

        # Number of deployment replicas
        replicas: 2

        # Indicates whether the container is running
        livenessProbe:
          # Number of seconds after the container has started before liveness probes are initiated
          initialDelaySeconds: 120
          # How often (in seconds) to perform the probe
          periodSeconds: 10
        # Indicates whether the container is ready to service requests
        readinessProbe:
          # Number of seconds after the container has started before readiness probes are initiated
          initialDelaySeconds: 120
          # How often (in seconds) to perform the probe
          periodSeconds: 10

        resources:
          # These are the resource recommendations for running WSO2 Open Banking Identity & Access Management Module profile
          # as per official documentation (https://docs.wso2.com/display/OB200/Open+Banking+Identity+and+Access+Management+High+Availability+Deployment#OpenBankingIdentityandAccessManagementHighAvailabilityDeployment-Deploymentprerequisites)
          requests:
            # The minimum amount of memory that should be allocated for a Pod
            memory: "3Gi"
            # The minimum amount of CPU that should be allocated for a Pod
            cpu: "3000m"
          limits:
            # The maximum amount of memory that should be allocated for a Pod
            memory: "4Gi"
            # The maximum amount of CPU that should be allocated for a Pod
            cpu: "4000m"
          # JVM settings
          # These are the resource allocation configurations associated with the JVM
          jvm:
            # Resource allocation for the Java Heap
            heap:
              memory:
                # Initial and minimum Heap size
                xms: "2048m"
                # Maximum Heap size
                xmx: "2048m"

        # Configure the WSO2 IS connector 
        connector:
          name: "wso2is-extensions"
          # Connector name
          version: "1.6.8"
          # The URL to download the IS connector
          url: "https://apim.docs.wso2.com/en/4.2.0/assets/attachments/administer/wso2is-extensions-1.6.8.zip"

        # Configure Ingress for Open Banking Identity & Access Management Module service
        ingress:
          # Ingress configurations for Open Banking Identity & Access Management Module service
          management:
            # Hostname for Open Banking Identity & Access Management Module service
            hostname: "obiam"
            # Annotations for the Open Banking Identity & Access Management Module service Ingress
            annotations:
              kubernetes.io/ingress.class: "nginx"
              nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
              nginx.ingress.kubernetes.io/affinity: "cookie"
              nginx.ingress.kubernetes.io/session-cookie-name: "route"
              nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
              nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      
      # Product configurations
      config:
        # Externalized data source configurations
        datasources:
          # RDBMS configurations
          rdbms:
            # RDBMS type
            type: "mysql"
            # RDBMS server configurations
            server:
              hostname: "wso2ob-rdbms-service-mysql"
              port: "3306"
              username: "wso2carbon"
              password: "wso2carbon"
            driverClassName: "com.mysql.jdbc.Driver"

kubernetes:
  # Name of Kubernetes service account
  serviceAccount: "wso2ob-pattern-5-svc-account"
