# -------------------------------------------------------------------------------------
#
# Copyright (c) 2023, WSO2 LLC. (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 LLC. and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained 
# herein is strictly forbidden, unless permitted by WSO2 in accordance with the 
# WSO2 Commercial License available at https://wso2.com/licenses/eula/3.2
#
# --------------------------------------------------------------------------------------

{{ if and .Values.wso2.deployment.persistence.solrIndexing.enabled .Values.gcp.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "am-all-in-one.fullname" . }}-local-carbon-database
  labels:
    purpose: am-carbondb
spec:
  capacity:
    storage: {{ .Values.gcp.fs.capacity }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: {{ template "am-all-in-one.fullname" . }}-sc
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: filestore.csi.storage.gke.io
    volumeHandle: "modeInstance/{{ .Values.gcp.fs.location }}/{{ .Values.gcp.fs.fileshares.carbonDB.fileStoreName }}/{{ .Values.gcp.fs.fileshares.carbonDB.fileShareName }}"
    volumeAttributes:
      ip: {{ .Values.gcp.fs.fileshares.carbonDB.ip }}
      volume: {{ .Values.gcp.fs.fileshares.carbonDB.fileShareName }}

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "am-all-in-one.fullname" . }}-solr-indexed-data
  labels:
    purpose: am-solr
spec:
  capacity:
    storage: {{ .Values.gcp.fs.capacity }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: {{ template "am-all-in-one.fullname" . }}-sc
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: filestore.csi.storage.gke.io
    volumeHandle: "modeInstance/{{ .Values.gcp.fs.location }}/{{ .Values.gcp.fs.fileshares.solr.fileStoreName }}/{{ .Values.gcp.fs.fileshares.solr.fileShareName }}"
    volumeAttributes:
      ip: {{ .Values.gcp.fs.fileshares.solr.ip }}
      volume: {{ .Values.gcp.fs.fileshares.solr.fileShareName }}

{{ end }}
