# ----------------------------------------------------------------------------------------
#
# Copyright (c) 2023, WSO2 LLC. (https://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 LLC. and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained
# herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
# You may not alter or remove any copyright or other notice from copies of this content.
#
# ----------------------------------------------------------------------------------------

apiVersion: v1
kind: Service
metadata:
  name: {{ template "ob-pattern-5.resource.prefix" . }}-obam-1-service
  namespace : {{ .Release.Namespace }}
spec:
  # label keys and values that must match in order to receive traffic for this service
  selector:
    deployment: {{ template "ob-pattern-5.resource.prefix" . }}-obam
    node: {{ template "ob-pattern-5.resource.prefix" . }}-obam-1
  ports:
    # ports that this service should serve on
    - name: binary
      protocol: TCP
      port: 9611
    - name: binary-secure
      protocol: TCP
      port: 9711
    - name: jms-tcp
      protocol: TCP
      port: 5672
    - name: servlet-https
      protocol: TCP
      port: 9443
